=== engsyst/ws_mvn/LB1.XMLXSD/xml/choice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://it.nure.ua/xmldemo/choce"
	xmlns:tns="http://it.nure.ua/xmldemo/choce" elementFormDefault="qualified">

	<complexType name="choice">
		<choice>
			<element name="from" type="string" />
			<element name="to" type="string" />
			<element name="copy" type="string" />
		</choice>
	</complexType>

	<element name="msg" >
		<complexType>
			<sequence>
				<element name="addr" type="tns:choice" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>

</schema>

=== engsyst/ws_mvn/LB1.XMLXSD/xml/choice.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:msg xmlns:tns="http://training.epam.com/xmldemo/choce" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://training.epam.com/xmldemo/choce choice.xsd ">
	<tns:addr>
		<tns:from>from</tns:from>
	</tns:addr>
	<tns:addr>
		<tns:to>to</tns:to>
	</tns:addr>
	<tns:addr>
		<tns:copy>copy</tns:copy>
	</tns:addr>
	<tns:addr>
		<tns:to>hidden copy</tns:to>
	</tns:addr>
</tns:msg>
