=== engsyst/ws_mvn/LB1.XMLXSD/xml/datetime.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://it.nure.ua/xmldemo"
	xmlns:tns="http://it.nure.ua/xmldemo" elementFormDefault="qualified">

	<complexType name="DateTime">
		<all>
			<element name="Duration" type="duration" />
			<element name="DateTime" type="dateTime" />
			<element name="Time" type="time" />
			<element name="YearMonth" type="gYearMonth" />
			<element name="MonthDay" type="gMonthDay" />
			<element name="Year" type="gYear" />
			<element name="Month" type="gMonth" />
			<element name="Day" type="gDay" />
		</all>
	</complexType>
	<element name="datetime" type="tns:DateTime"></element>
</schema>

=== engsyst/ws_mvn/LB1.XMLXSD/xml/datetime.xml
<?xml version="1.0" encoding="UTF-8"?>
<datetime xmlns="http://training.epam.com/xmldemo"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://training.epam.com/xmldemo datetime.xsd ">
	<Duration>P1D</Duration>
	<DateTime>2001-12-31T12:00:00</DateTime>
	<Time>12:00:00</Time>
	<YearMonth>2001-01</YearMonth>
	<MonthDay>--01-01</MonthDay>
	<Year>2001</Year>
	<Month>--01</Month>
	<Day>---01</Day>
</datetime>
