=== engsyst/ws_mvn/LB1.XMLXSD/xml/unique.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/unique"
	xmlns:tns="http://www.example.org/unique">

	<xs:element name="order" type="tns:Order">
		<xs:unique name="uniqueProducts">
			<xs:annotation><xs:documentation>
			Requires unique identifiers across the order. 
			Must be located in an element within which 
			uniqueness will be ensured.
			</xs:documentation></xs:annotation>
			<xs:selector xpath=".//product" />
			<xs:field xpath="@id" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="Order">
		<xs:sequence>
			<xs:element name="item" type="tns:Item"
				maxOccurs="unbounded" />
			<xs:element name="total" type="xs:decimal" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required" />
	</xs:complexType>

	<xs:complexType name="Item">
		<xs:sequence>
			<xs:element name="product" type="tns:Product" />
			<xs:element name="count" type="xs:int" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Product">
		<xs:sequence>
			<xs:element name="name" type="xs:token" />
			<xs:element name="description" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required" />
	</xs:complexType>

</xs:schema>

=== engsyst/ws_mvn/LB1.XMLXSD/xml/unique.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:order id="0"
	xmlns:tns="http://www.example.org/unique"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/unique unique.xsd ">

	<!-- Try to make non-unique product @id -->
	<item>
		<product id="0">
			<name>token</name>
			<description>description</description>
		</product>
		<count>0</count>
	</item>
	<item>
		<product id="1">
			<name>token</name>
			<description>description</description>
		</product>
		<count>0</count>
	</item>
	<total>0.0</total>
</tns:order>
